POST http://localhost:3000/api/employees
Content-Type: application/json

{
    "firstName": "Rich",
    "middleName": ".",
    "lastName": "Com",
    "emailAddress": "rich@wealthy.com",
    "position": "CEO"
}
###
POST http://localhost:3000/api/signup
Content-Type: application/json

{
    "emailAddress": "rich@wealthy.com",
    "password": "rich.com"
}

###
GET http://localhost:8080/api/employees/email/kintehfatima@gmail.com
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4NzE4MzJmZTY0MDNkNjQzZGE0NjQ4ZCIsImVtYWlsQWRkcmVzcyI6ImtpbnRlaGZhdGltYUBnbWFpbC5jb20iLCJyb2xlIjoiU1RBRkYiLCJpYXQiOjE3NTIyNzk4MzcsImV4cCI6MTc1MjM2NjIzN30.2iE7zk9fLPupdXE9oU-zTsSaseAQVwPabIPrUxAtF7A
###

GET http://localhost:8080/api/attendance/employee?employeeId=2&date=2025-07-12
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4NzE4MzJmZTY0MDNkNjQzZGE0NjQ4ZCIsImVtYWlsQWRkcmVzcyI6ImtpbnRlaGZhdGltYUBnbWFpbC5jb20iLCJyb2xlIjoiU1RBRkYiLCJpYXQiOjE3NTIyNzk4MzcsImV4cCI6MTc1MjM2NjIzN30.2iE7zk9fLPupdXE9oU-zTsSaseAQVwPabIPrUxAtF7A
###
POST http://localhost:8080/api/attendance/clock-out/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4NzE4MzJmZTY0MDNkNjQzZGE0NjQ4ZCIsImVtYWlsQWRkcmVzcyI6ImtpbnRlaGZhdGltYUBnbWFpbC5jb20iLCJyb2xlIjoiU1RBRkYiLCJpYXQiOjE3NTIyODUwNDIsImV4cCI6MTc1MjM3MTQ0Mn0.TBAfAyzQ3JH8pSC6MxuiA9s22QEGqO-Fu6LbUmvhq-M
